<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <ItemGroup>
    <ProjectReference Include="..\ApiAggregator\ApiAggregator.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>9b9bd88c-e72c-4547-b900-8495973f1c8f</UserSecretsId>
  </PropertyGroup>

</Project>
